name: CI

on: push

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Cache node_modules
        uses: actions/cache@v3
        id: node_modules_cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: type check
        run: npx tsc --noEmit
      - name: lint
        run: npx eslint .
      - name: format
        run: npx prettier --check --ignore-unknown .
      - name: test
        run: npx vitest related --run
